#!groovy

// Generated by IBM TransformationAdvisor
// Thu Jan 17 13:50:53 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}